### ISSUE TITLE
たまに音楽が流れなくなる時がある

### ISSUE THREAD

**Issue by nooneMona** [nooneMona/nitouheDiscordBot#28]
cancelもclearもしてないのに事象発生

**Comment by iwamizawa-software** [comment]
iwamizawa-jukeで治ったかもしれない

**Comment by kisschan** [comment]
おう

**Comment by nooneMona** [comment]
なんできすけが自分にアサインしてるのｗ

とりあえずこれは、
- IP制限にひっかかるやつは流れない #34 
- Promiseの対応漏れ #29 
これで一応対応できたと思うのでClose
