### ISSUE TITLE
リアクションに反応できるようにしたい

### ISSUE THREAD

**Issue by kisschan** [nooneMona/nitouheDiscordBot#41]
リアクションに反応するためには、messagereactionaddのイベントが必要らしい

**Comment by nooneMona** [comment]
うむ、`main.js`から購読しよう。

**Comment by kisschan** [comment]
なにそれしらん

**Comment by nooneMona** [comment]
すまんミスった`index.js`

**Comment by kisschan** [comment]
いや、皮肉かもしれん……。許せんなー!!!!
Index.jsもう見た。まぁとりあえずIndex.jsだけいじってみようかな

**Comment by nooneMona** [comment]
皮肉ではないｗ
`messageReplyer`にonReactionAddedみたいなメソッド作って、

```
client.on('messagerRactionadd', (msgReaction, user) => async {
  messageReplyer.onReactionAdded(msgReaction, user);
})
```
こんな感じにするといいかおｍ
