### ISSUE TITLE
２回目になったらDMで警告打つのはどう

### ISSUE THREAD

**Issue by nooneMona** [nooneMona/nitouheDiscordBot#77]
２回目になったらDMで警告打つのはどう

_Originally posted by @nooneMona in https://github.com/nooneMona/nitouheDiscordBot/pull/75#discussion_r579831380_

**Comment by iwamizawa-software** [comment]
いいかもしれないがｄｍ大量発行することになるかもしれない
それで動作が遅延すると困ることになる

**Comment by nooneMona** [comment]
確かにな。
