### ISSUE TITLE
ここに荒らしが入り込んでBOTが落ちる可能性は考慮したほうがいい気がするな

### ISSUE THREAD

**Issue by nooneMona** [nooneMona/nitouheDiscordBot#78]
ここに荒らしが入り込んでBOTが落ちる可能性は考慮したほうがいい気がするな

_Originally posted by @nooneMona in https://github.com/nooneMona/nitouheDiscordBot/pull/75#discussion_r579830032_

**Comment by iwamizawa-software** [comment]
Herokuのほうで死んだら再起動かけるみたいなのないの

**Comment by nooneMona** [comment]
あった気がする
